// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKC2r9va-EKt-0i3iYLAQSMGNAoeFdOk4',
    appId: '1:520256872696:web:24f96e385af83f149fdb0d',
    messagingSenderId: '520256872696',
    projectId: 'bitcot-shopping-ecommerce-app',
    authDomain: 'bitcot-shopping-ecommerce-app.firebaseapp.com',
    storageBucket: 'bitcot-shopping-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC263-VrW5O5Zu5TlCzw4CGCYC5Lq-qAF0',
    appId: '1:520256872696:android:100887f1ac9ad5c29fdb0d',
    messagingSenderId: '520256872696',
    projectId: 'bitcot-shopping-ecommerce-app',
    storageBucket: 'bitcot-shopping-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eNkg2kWra93GrW6NcofswZp33yUZJUc',
    appId: '1:520256872696:ios:49f0887a3a7a72119fdb0d',
    messagingSenderId: '520256872696',
    projectId: 'bitcot-shopping-ecommerce-app',
    storageBucket: 'bitcot-shopping-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7eNkg2kWra93GrW6NcofswZp33yUZJUc',
    appId: '1:520256872696:ios:49f0887a3a7a72119fdb0d',
    messagingSenderId: '520256872696',
    projectId: 'bitcot-shopping-ecommerce-app',
    storageBucket: 'bitcot-shopping-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKC2r9va-EKt-0i3iYLAQSMGNAoeFdOk4',
    appId: '1:520256872696:web:8988602a5a8933a49fdb0d',
    messagingSenderId: '520256872696',
    projectId: 'bitcot-shopping-ecommerce-app',
    authDomain: 'bitcot-shopping-ecommerce-app.firebaseapp.com',
    storageBucket: 'bitcot-shopping-ecommerce-app.firebasestorage.app',
  );
}
